#!/usr/bin/env python3
"""
Quick start guide for YNAB integration.

This script helps you set up the YNAB API integration step by step.

Usage:
  python3 setup_ynab.py
"""
import os
import sys
from pathlib import Path
from ynab_api import YNABClient, YNABAuthError


def print_header(text: str):
    """Print formatted header."""
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60)


def print_step(number: int, text: str):
    """Print formatted step."""
    print(f"\n[{number}] {text}")
    print("-" * 60)


def setup_interactive():
    """Interactive setup wizard."""
    
    print_header("YNAB Integration Setup")
    print("\nThis wizard will help you configure YNAB integration.")
    print("You'll need your YNAB API token from https://app.ynab.com/settings/developer")
    
    # Step 1: Get API Token
    print_step(1, "Get API Token")
    print("Go to https://app.ynab.com/settings/developer")
    print("Click 'Generate New Token' and copy it")
    api_token = input("\nEnter your YNAB API token: ").strip()
    
    if not api_token:
        print("Error: API token is required")
        return False
    
    # Step 2: Verify token
    print_step(2, "Verify API Token")
    print("Connecting to YNAB API...")
    
    try:
        with YNABClient(api_token) as client:
            budgets = client.get_budgets()
            print(f"✓ Successfully connected to YNAB!")
            print(f"Found {len(budgets)} budget(s)")
    except YNABAuthError:
        print("✗ Invalid API token. Please check and try again.")
        return False
    except Exception as e:
        print(f"✗ Error: {e}")
        return False
    
    # Step 3: Select budget
    print_step(3, "Select Budget")
    
    if not budgets:
        print("No budgets found in your YNAB account")
        return False
    
    for i, budget in enumerate(budgets, 1):
        print(f"{i}. {budget['name']} (ID: {budget['id']})")
    
    while True:
        try:
            choice = int(input("\nSelect budget number: "))
            if 1 <= choice <= len(budgets):
                selected_budget = budgets[choice - 1]
                break
            else:
                print("Invalid selection")
        except ValueError:
            print("Please enter a valid number")
    
    budget_id = selected_budget["id"]
    print(f"✓ Selected: {selected_budget['name']}")
    
    # Step 4: Select accounts
    print_step(4, "Select Accounts")
    print(f"Getting accounts for '{selected_budget['name']}'...")
    
    try:
        with YNABClient(api_token) as client:
            accounts = client.get_accounts(budget_id)
            print(f"Found {len(accounts)} account(s):")
    except Exception as e:
        print(f"Error: {e}")
        return False
    
    account_mapping = {}
    
    # Define expected bank/account names
    expected_accounts = [
        "OCBC_DEFAULT",
        "POSB_EVERYDAY_USE", 
        "POSB_MY_SAVINGS",
    ]
    
    for i, account in enumerate(accounts, 1):
        print(f"{i}. {account['name']} (ID: {account['id']})")
    
    print("\nMap your bank accounts to YNAB accounts (or skip):")
    
    for env_var in expected_accounts:
        print(f"\n{env_var}:")
        for i, account in enumerate(accounts, 1):
            print(f"  {i}. {account['name']}")
        print(f"  0. Skip")
        
        while True:
            try:
                choice = int(input(f"Select account number (0 to skip): "))
                if choice == 0:
                    break
                elif 1 <= choice <= len(accounts):
                    account_mapping[env_var] = accounts[choice - 1]["id"]
                    print(f"✓ Mapped {env_var} -> {accounts[choice - 1]['name']}")
                    break
                else:
                    print("Invalid selection")
            except ValueError:
                print("Please enter a valid number")
    
    # Step 5: Save configuration
    print_step(5, "Save Configuration")
    
    env_content = f"""# YNAB API Configuration
# Generated by setup_ynab.py

YNAB_API_TOKEN={api_token}
YNAB_BUDGET_ID={budget_id}

# Account mappings
"""
    
    for env_var, account_id in account_mapping.items():
        env_content += f"{env_var}={account_id}\n"
    
    # Check if .env exists
    env_path = Path(".env")
    if env_path.exists():
        print(f"File .env already exists")
        overwrite = input("Overwrite? (y/n): ").strip().lower()
        if overwrite != "y":
            print("Keeping existing .env file")
            return False
    
    with open(".env", "w") as f:
        f.write(env_content)
    
    print(f"✓ Configuration saved to .env")
    
    # Step 6: Test upload
    print_step(6, "Test Configuration")
    print("Your configuration is ready!")
    print("\nNext steps:")
    print("1. Place your bank CSV files in: data/incoming/")
    print("2. Run: python3 process_ynab.py")
    print("3. Test upload: python3 ynab_uploader.py --dry-run")
    print("4. Upload: python3 ynab_uploader.py")
    
    return True


def main():
    """Main entry point."""
    try:
        if setup_interactive():
            print_header("Setup Complete!")
            print("✓ Configuration saved successfully")
            return 0
        else:
            print_header("Setup Cancelled")
            return 1
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user")
        return 1
    except Exception as e:
        print(f"\nError: {e}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
